### ISSUE TITLE
Integration and Staging are Failing to Deploy after the Travis Build

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#197]
Hi There, Staging and Integration build but do not deploy.
https://travis-ci.org/HumanCellAtlas/data-portal/builds/409834752
https://travis-ci.org/HumanCellAtlas/data-portal/builds/409834850

Develop is fine:
https://travis-ci.org/HumanCellAtlas/data-portal/builds/409834377

**Comment by NoopDog** [comment]
Hi Parth,

Do you have time to take a look at these? Now that I am actually starting to use these environments it seems they are not deploying. Looks like an AWS copy to cloudflare problem?

I have copied the URLs in travis of the borked (staging and integration)  and working (develop) environments. 

Cheers and Thanks,
Dave

**Comment by parthshahva** [comment]
@NoopDog It looks like integration and dev are fine. Staging is having issues because the make deploy command for staging is using the old npm way. https://github.com/HumanCellAtlas/data-portal/blob/staging/Makefile#L11 should be updated with public/ instead of site/ like https://github.com/HumanCellAtlas/data-portal/blob/staging/Makefile#L11

**Comment by parthshahva** [comment]
Only took a second so went ahead and fixed it in develop at https://github.com/HumanCellAtlas/data-portal/commit/4107ddc23642175f9b8d213392a760d8ba375b2a. Once developer is upmerged to integration and staging this will be resolved. You could also cherrypick this commit into staging.

**Comment by NoopDog** [comment]
Thanks @parthshahva this is working. Cheers! D
