### ISSUE TITLE
Edit organs on male/female body diagrams

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#225]
Putting the brain on the male body diagram and the heart on the female body has caused some negative comments from users.  We should switch these.

**Comment by NoopDog** [comment]
Ok thx for the feedback. Will get this updated.

**Comment by zperova** [comment]
May I suggest to add to both rather than switching them? Switching them might cause negative feedback as well. Also, having organ's in both diagram's indicates that the samples are coming from both female and male donors and is a better representation of the data we have. Having it only in one diagram suggests that the donors are either male or female.

**Comment by adriennes** [comment]
@zperova  - Agree that this solution has some advantages, but showing all organs on both bodies will make the diagrams very crowded/ difficult to select the right organ.   We will explore some other options for the diagram in the coming months, since there are some flaws with the current body diagrams.

**Comment by zperova** [comment]
@adriennes - exploring other options will be good!

**Comment by NoopDog** [comment]
Home page was re-implemented. This is no longer an issue. Closing.
