### ISSUE TITLE
Banners on Portal when parts of DCP are down

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/data-portal#243]
Now that the status API exists to make the status page https://github.com/HumanCellAtlas/status-api we should use this to create banners on the DCP portal for when particular prod services are down. Of course when the portal is down, that won't help. If the portal is down, is it possible to have the site show a link to the status page?

This banner functionality will also be needed during maintenance windows, likely before they start to warn users.

AC:
Users are informed of DCP prod downtime

@theathorn making this ticket here as I originally had it in DCP backlog and it didn't seem cross-cutting enough. Let me know if I am wrong on that.

https://status.dev.data.humancellatlas.org/service/dcp-health-check-dev

**Comment by sampierson** [comment]
Suggest post-GA?

**Comment by NoopDog** [comment]
@adriennes @theathorn After speaking with @mweiden I think we can support the following flow:

1) User comes to data portal, data portal checks a system wide aggregate health check for its environment (dev, int, prod etc)

2) If one of the aggregate health checks indicates that one of the systems is down we show a banner with a message and a link to a page that shows the detail  status of each system in the aggregate. 

I can suggest text for the banner:

"One or more of the systems composing the HCA DCP is currently unavailable. Full system status is available "here".

Does the above sound about right? What else might we do or how might we update the text?

If we want this on the browser as well lets open a separate ticket. We only need the status check on the browser and can send it to the status page on the portal.

**Comment by adriennes** [comment]
This sounds good.  It probably would be good to have the error message appear on the data browser as well, I suspect many people will bookmark the data browser page and start there once they are used to the portal.  

A couple thoughts on the message itself: 

- Can we add a symbol or icon (the classic exclamation mark in a triangle, maybe?) to catch peoples' attention and let them know this is an error? 
- I would slightly rephrase the second sentence, since right now we're pushing people to check the system status and many users won't know what to do with that.  I'd say, "Please try again later, or monitor the full system status here."
