### ISSUE TITLE
Change File Types labels in data browser

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-portal#250]
Labels "Primary" and "2nd" are confusing to users, especially since we are no longer using "secondary analysis" to refer to pipeline processing.  These should be changed- one suggestion is "Raw" and "Processed" 

@jodihir  to suggest new labels

**Comment by jodihir** [comment]
Raw and Processed seems most consistent with the rest of the portal.  I do wonder if "File Types" is confusing to users (it suggests file formats) and wonder if just having the word "Data" would be more enough.  So it would read: Data: Raw or Data: Processed instead of File Types: Raw or File Types: Processed.

**Comment by jodihir** [comment]
Moved to "in Progress"; I've added my thoughts above.

**Comment by theathorn** [comment]
This needs to be in the data-browser repo...

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/266.
