### ISSUE TITLE
Update Contributing landing page

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-portal#273]
This PR is related to the [data-portal-content PR #166](https://github.com/HumanCellAtlas/data-portal-content/pull/166) 

This PR requires the following updates to the page layout:
- [x] Removal of the /contribute/overview/what-to-prepare link in the left-hand navigation
- [x] Probably removal of the whole left-hand navigation since there will now only be 1 element in it
- [x] Moving of the `contact-us.md`, `prepare-metadata.md`, `upload-data.md`, and `see-and-share.md` icons to the spot indicated in the `content/contribute/overview/overview.md` document
- [x] Removal of the "The Atlas is built by the Community" title and the image directly below it

**Comment by malloryfreeberg** [comment]
Update looks great!

The last bit is to add back the 4 icons describing the contribution process. The icon images should still be in the same folder. Please place them here:

![screen shot 2018-10-25 at 09 11 51](https://user-images.githubusercontent.com/10993501/47485475-0e076780-d836-11e8-83d9-8389c5c35380.png)

Thanks!

**Comment by NoopDog** [comment]
HI @malloryfreeberg  I am wondering  if this section is a bit redundant and can be cut?

1. see and share - we already have links to explore in the header
1. contact us - already exists on in the footer and in the call to action "start by emailing " at the bottom of the page.
1. upload data - My understanding there is no public ingest at the moment and I think this goes to a holding page.
1. prepare metadata - we have that already on the page. 

Perhaps these sections areas could be detailed out in the contributing page instead of linking out elsewhere?

Would be great if we can get the contribute page to stay in the format of the other content pages. 

Cheers, 
Dave

**Comment by malloryfreeberg** [comment]
Hi @NoopDog 

@gabsie did have some thoughts on these icons that I neglected to share:

> We need another icon here to show the analysis process. We also need to remove the links at the bottom, but introduce this text in a more actionable way - work with Dave and Fran

So, I think the links **can** be removed from the bottom of the icons. One benefit of having the icons is to break up the column of text and make the contribute process feel friendlier by providing a visual to correspond to the text. 

I'll let @gabsie comment on the need for a fifth "analyze" icon.

**Comment by NoopDog** [comment]
I see, yes we can create an image that shows the "lifecycle" and then embed that image in the page with the normal markdown image embedding.

**Comment by NoopDog** [comment]
That said... ;) It seems we already have this on the home page?


<img width="953" alt="screen shot 2018-10-25 at 6 34 49 pm" src="https://user-images.githubusercontent.com/3239697/47486924-c2c87580-d884-11e8-915a-0fd56ceb8487.png">

Maybe the contribute section can be tightly focused on the contributing process and we can avoid expanding the scope of this page?

If we were to have a diagram, perhaps it could be focused on the steps of contributing rather than trying to place "contributing" in the context of the entire effort?

WDYT?

**Comment by theathorn** [comment]
@malloryfreeberg can we close this and continue with the UX Content Review?
https://app.zenhub.com/workspace/o/humancellatlas/data-portal-content/issues/150

**Comment by malloryfreeberg** [comment]
@theathorn we still need to address the third point in this ticket about the icons.

@NoopDog I think your point of not duplicating info is a good one. Could we then have the "Contact us", "Prepare metadata", and "Upload data" icons here?

@gabsie might also suggest having a final icon to indicate an "Approve submission" step, but we would have to ask someone to make it.

After the 3 (4?) icons are added to the page, we can close this ticket.

**Comment by gabsie** [comment]
Hi, everyone

I think we are OK with the old icons for the time being (if we cannot get a Pipeline processing icon soon), but yes please let's remove the links under them.

 The step about approval, @malloryfreeberg - I wouldn't show this as this is supposed to be normal functionality, not a significant step or a "benefit". which the analysis is supposed to be.

However, @NoopDog - I do want to have the two prompts for emailing the data-help in some standing out style (not sure if you have call to action type boxes of a kind).

Let me know if questions!
Gabby

**Comment by malloryfreeberg** [comment]
@gabsie are you ok with removing the "see and share" icon now? Since this isn't a part of the contribution process.

I think we don't need the "Pipeline processing" icon here either, since this is also not part of the contributing process (but comes later). "Pipeline processing" icon is already on the main page, as well.

**Comment by gabsie** [comment]
No, let's leave them as they are - See and share is important :) - it gives people an idea of an ending.

**Comment by theathorn** [comment]
Moving back to In Progress for final icon determination..

**Comment by malloryfreeberg** [comment]
Looks good!
