### ISSUE TITLE
Update hover text for "Known Diseases" column

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#427]
Currently the "Known Diseases" hover says "Free text describing any diseases association to the cell type. Should be an EFO ontology."

I am feeling like this is old and should also reference that this is the specimen diseases and not the donor_organism diseases.

Proposing changing this to:

"Short description of known disease(s) of the specimen."

@malloryfreeberg does this change make sense to you or should we leave this or change to something else?

**Comment by NoopDog** [comment]
Oh also, @malloryfreeberg @adriennes we do not display disease on donor_organism on any table or currently have this as a facet. Is there interest in listing donor_organism diseases and faceting on them?

**Comment by malloryfreeberg** [comment]
@NoopDog That description is fine.

Alternatively, you can grab the [description](https://github.com/HumanCellAtlas/metadata-schema/blob/ec5f13c8278be46d2ac943ee43bf5f360eb54c01/json_schema/type/biomaterial/specimen_from_organism.json#L69) directly from the specimen schema:

```
        "diseases": {
            "description": "Short description of known disease(s) of the specimen.",
            "type": "array",
            "items": {
                "$ref": "module/ontology/disease_ontology.json"
	        },
            "user_friendly": "Known disease(s)",
            "guidelines": "Enter normal if no known diseases."
        },
```

The donor schema has a similar description for disease, but it says "of the organism" instead of "of the specimen", thus distinguishing between the two if yo want to display both.

The current description in the hover looks like it was pulled from an older version of the schema, so I would highly recommend getting the values from the schema itself, so in case we update it, the Browser (and Metadata Dictionary) all display the same value.

**Comment by malloryfreeberg** [comment]
> Is there interest in listing donor_organism diseases and faceting on them?

I can see arguments for many sides for this one, with the following options:
1. Display/facet only donor known diseases
1. Display/facet only specimen known diseases
1. Display/facet both donor and specimen diseases

I honestly don't know between options 1 and 2 which is more useful for people browsing the datasets. Option 3 is nice as it gives the full picture of what the data are representing, but this is more complex than options 1 or 2 and so we would need to telegraph clearly to people what the two different values mean (could be challenging).

I'm curious to hear what others (@gabsie @adriennes @HumanCellAtlas/wranglers @HumanCellAtlas/metadata-updates ) think about this.

**Comment by claymfischer** [comment]
When this was discussed at the 2018 November F2F in Boston, @adriennes had a wonderful ending statement of simply having a "see all facets" option where the donor's health would be shown. It was hoped this would be less confusing to users by not having a default facet for two disease states.

Not sure if this has been discussed since.

**Comment by adriennes** [comment]
Agree with Mallory's assessment above: both donor and specimen level diseases are necessary to fully capture what's going on in the data, but it introduces a lot of complexity for users, and is a lot to disambiguate at first glance.  Like @claymfischer says, the best way to do this might be to hide the donor's health (since this is probably the less important of the two pieces of information) and make it viewable under advanced settings.
