### ISSUE TITLE
Create a dataset-questionnaire page that links to our google form

### ISSUE THREAD

**Issue by mshadbolt** [DataBiosphere/data-portal#613]
Currently we have a google form that contributors fill in which gives us an idea of the type of data they want to submit and allows us to prepare a template spreadsheet.

Currently we circulate a tinyurl because the google form url is long and unwieldy. There are a few reasons why tinyurl links are not the best so we would like to create a page:
https://data.humancellatlas.org/contribute/dataset-questionnaire
that would re-direct to view and complete the google form.

The link the above page would redirect to would be the view link to complete the form:
https://docs.google.com/forms/d/e/1FAIpQLSdjPk2Z6xYozds53ycvXo57PvFsyqOF6XMpSWCVNTpQYalZzQ/viewform

This will give us the ability to update the link in future and provide a more stable and trustworthy link to contributors.

(tag @gabsie)

**Comment by NoopDog** [comment]
Hi  @ mshadbolt would you be ok without the redirect? If we had just a page https://data.humancellatlas.org/contribute/dataset-questionnaire that had some introductory text and then a link, that would be easier to create and would be maintainable by the content team. Otherwise we need to start updating DNS records to do the redirects etc. 

Rather than mimic the tiny url setup (which we are not setup to do) let's try a page with a link.  Does that sound like something that will solve this use case?

Cheers,
D

**Comment by mshadbolt** [comment]
Hi @NoopDog , yes that sounds like it would be a good solution. I didn't realise the technicalities of a redirect, I think your suggestion will work perfectly well.
Cheers,
Marion

**Comment by NoopDog** [comment]
Hi @mshadbolt is still something we still want to implement? I have moved this out of the icebox and we can prioritize if this is still desired. Is the link still valid?

Cheers,
D

**Comment by mshadbolt** [comment]
hi @NoopDog , let me get back to you on this before you start working on it as we have been working on improving our UI so might be implementing there instead.
Cheers, Marion

**Comment by NoopDog** [comment]
Obsolete we can re-open if this becomes a requirement
