### ISSUE TITLE
Privacy - UCSC: Update GDPR Privacy notice for DCP/2 MVP

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-portal#725]
Current [Privacy notice](https://data.humancellatlas.org/privacy).

[This](https://docs.google.com/document/d/1gp_BgtFl8-m0F14voaFpnbMbYLgCd2rIYnSQEgX1VOE) needs to be updated to reflect UCSC's current policy and approved by the UCSC Data Protection Officer.

EBI and the Broad will supply their own privacy statements.

**Comment by theathorn** [comment]
This is for the DCP 2.0 release for open access data only.

**Comment by NoopDog** [comment]
@theathorn @nolunwa Is there any update to the UCSC privacy doc required for the DCP2 MVP? (non controlled access)

The current privacy notice is here:
https://data.humancellatlas.org/privacy

**Comment by theathorn** [comment]
@nolunwa we need to finalize our [new GDPR statement](https://docs.google.com/document/d/1gp_BgtFl8-m0F14voaFpnbMbYLgCd2rIYnSQEgX1VOE).
I asked Tony Burdett about waiting for approval from the GDPR Working Group and he replied "I would say the answer is no, we're not waiting and we should deploy with the MVP".

**Comment by nolunwa-ucsc** [comment]
Hello Dave and Trevor,

The GDPR Statement has already been approved by UCSC and can be publicly
facing no further action from me or Denise (UCSC Privacy Officer).

Thanks

Warm Regards
*Nneka Olunwa*
*Security & Compliance Officer*
*https://ucscgenomics.soe.ucsc.edu/ <https://ucscgenomics.soe.ucsc.edu/>*



This document contains information belonging to the Dockstore system and
HCA project which may be confidential and legally privileged. This
information is only for the use of the individual or entity to which it was
intended. Any disclosure, copying, distribution, or action taken in
reliance on the contents of the information contained in this document and
any accompanying documents is strictly prohibited unless otherwise
authorized by System administrators.

**Comment by NoopDog** [comment]
@theathorn can this be closed for MVP?

**Comment by theathorn** [comment]
We  should switch to the new [UCSC GDPR statement](https://docs.google.com/document/d/1gp_BgtFl8-m0F14voaFpnbMbYLgCd2rIYnSQEgX1VOE).

**Comment by NoopDog** [comment]
@theathorn 

Replace https://data.humancellatlas.org/privacy

With https://docs.google.com/document/d/1gp_BgtFl8-m0F14voaFpnbMbYLgCd2rIYnSQEgX1VOE/edit ?

**Comment by NoopDog** [comment]
@theathorn This is on cgl dev for your review. Let me now if you want any updates to the intro material. 

https://dev.singlecell.gi.ucsc.edu/privacy

**Comment by theathorn** [comment]
LGTM.

**Comment by NoopDog** [comment]
Deployed
https://data.humancellatlas.org/privacy
