### ISSUE TITLE
Review Portal Implementation and Create Issues

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-portal#84]

**Comment by happyimadesignr** [comment]
Here's my review of the Browser. I marked a "P" in front of the items that are priority to me.

* P - Data Browser - Make filters, counts, download button sticky. See design: https://chanzuckerberg.invisionapp.com/share/JQKKKO4B6Z5#/297570103_2-2-1_Explore_-_Data_Copy_17
* Data Browser - Tooltip animation too extreme
* Data Browser - Pagination needs to be updated. See design: https://chanzuckerberg.invisionapp.com/share/UQKKKQKWKFH#/299232552_2-0-0_Explore_-_Data_Copy_2
* P - Data Browser - Pagination - Remove top pagination
* Data Browser - Table needs to match design
* P - Data Browser - Filters - Method is missing Molecule and Sequencing Approach. Imaging Approach for later.
* P - Data Browser - Filters - We need friendly names from Ingest team ASAP 
* P - Data Browser - Filters - Donor filter dropdown should be 4 across rather than 3.
* P - Data Browser - Filters - Specimen is missing Specimen Type and Storage Method
* P - Data Browser - Filters - More dropdown - Terms under Protocol should wrap to 2nd line rather than “..."
* P - Data Browser - Filters - All dropdown titles should wrap to 2nd line rather than "..."
* P - Data Browser - Filters - Fix how ages are displayed. At least should be in order from lowest to highest.
* Data Browser - Filters - Needs heavier type weight
* Data Browser - Filters -  Move arrow to the right so the right and left margin looks the same.
* Data Browser - Filter Tags - Capitalize the facet.
* Data Browser - Filter Tags - Need friendly terms for facets.
* Data Browser - Download button - remove drop shadow
* Data Browser - Download button - remove Material animation
* Data Browser - Download button - needs hover state
* Data Browser - Download button - heavier type weight
* Data Browser - Table - Typography needs to be updated, weights and color
* Data Browser - Table - Lines between table line items should be thicker, match design
* Data Browser - Table - Increase to 15 line items on the table

**Comment by NoopDog** [comment]
Thanks Jenn!

------------------------------
Dave Rogers
Partner, Clever Canary
646-286-5371
http://clevercanary.com

@CleverCanary
@_DaveRogers
https://www.linkedin.com/pub/dave-rogers/0/90/92


On Jun 9, 2018, at 9:20 AM, Jennifer Tang <notifications@github.com> wrote:

Here's my review of the Browser. I marked a "P" in front of the items that
are priority to me.

   - P - Data Browser - Make filters, counts, download button sticky. See
   design:
   https://chanzuckerberg.invisionapp.com/share/JQKKKO4B6Z5#/297570103_2-2-1_Explore_-_Data_Copy_17
   - Data Browser - Tooltip animation too extreme
   - Data Browser - Pagination needs to be updated. See design:
   https://chanzuckerberg.invisionapp.com/share/UQKKKQKWKFH#/299232552_2-0-0_Explore_-_Data_Copy_2
   - P - Data Browser - Pagination - Remove top pagination
   - Data Browser - Table needs to match design
   - P - Data Browser - Filters - Method is missing Molecule and Sequencing
   Approach. Imaging Approach for later.
   - P - Data Browser - Filters - We need friendly names from Ingest team
   ASAP
   - P - Data Browser - Filters - Donor filter dropdown should be 4 across
   rather than 3.
   - P - Data Browser - Filters - Specimen is missing Specimen Type and
   Storage Method
   - P - Data Browser - Filters - More dropdown - Terms under Protocol
   should wrap to 2nd line rather than “..."
   - P - Data Browser - Filters - All dropdown titles should wrap to 2nd
   line rather than "..."
   - P - Data Browser - Filters - Fix how ages are displayed. At least
   should be in order from lowest to highest.
   - Data Browser - Filters - Needs heavier type weight
   - Data Browser - Filters - Move arrow to the right so the right and left
   margin looks the same.
   - Data Browser - Filter Tags - Capitalize the facet.
   - Data Browser - Filter Tags - Need friendly terms for facets.
   - Data Browser - Download button - remove drop shadow
   - Data Browser - Download button - remove Material animation
   - Data Browser - Download button - needs hover state
   - Data Browser - Download button - heavier type weight
   - Data Browser - Table - Typography needs to be updated, weights and
   color
   - Data Browser - Table - Lines between table line items should be
   thicker, match design
   - Data Browser - Table - Increase to 15 line items on the table

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HumanCellAtlas/data-portal/issues/84#issuecomment-395917608>,
or mute the thread

**Comment by happyimadesignr** [comment]
Added list here: https://docs.google.com/document/d/1eeh6Ohu8rbmwjH1yGdf07P7WmHAQpYLYeVrVTXTBaVQ/edit?ts=5b186426#heading=h.3rd18eeugcc5

@frano-m
